/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as Soul_gameRouteImport } from './routes/soul_game'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIndexRouteImport } from './routes/session/index'
import { Route as SessionListRouteImport } from './routes/session/list'
import { Route as SessionJoinRouteImport } from './routes/session/join'
import { Route as SessionCreateRouteImport } from './routes/session/create'
import { Route as MapSessionIdRouteImport } from './routes/map.$sessionId'
import { Route as Soul_gameChatSessionIdRouteImport } from './routes/soul_game.chat.$sessionId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const Soul_gameRoute = Soul_gameRouteImport.update({
  id: '/soul_game',
  path: '/soul_game',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIndexRoute = SessionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionRoute,
} as any)
const SessionListRoute = SessionListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => SessionRoute,
} as any)
const SessionJoinRoute = SessionJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => SessionRoute,
} as any)
const SessionCreateRoute = SessionCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SessionRoute,
} as any)
const MapSessionIdRoute = MapSessionIdRouteImport.update({
  id: '/map/$sessionId',
  path: '/map/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const Soul_gameChatSessionIdRoute = Soul_gameChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => Soul_gameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/session': typeof SessionRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/soul_game': typeof Soul_gameRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/map/$sessionId': typeof MapSessionIdRoute
  '/session/create': typeof SessionCreateRoute
  '/session/join': typeof SessionJoinRoute
  '/session/list': typeof SessionListRoute
  '/session/': typeof SessionIndexRoute
  '/soul_game/chat/$sessionId': typeof Soul_gameChatSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/soul_game': typeof Soul_gameRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/map/$sessionId': typeof MapSessionIdRoute
  '/session/create': typeof SessionCreateRoute
  '/session/join': typeof SessionJoinRoute
  '/session/list': typeof SessionListRoute
  '/session': typeof SessionIndexRoute
  '/soul_game/chat/$sessionId': typeof Soul_gameChatSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/session': typeof SessionRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/soul_game': typeof Soul_gameRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/map/$sessionId': typeof MapSessionIdRoute
  '/session/create': typeof SessionCreateRoute
  '/session/join': typeof SessionJoinRoute
  '/session/list': typeof SessionListRoute
  '/session/': typeof SessionIndexRoute
  '/soul_game/chat/$sessionId': typeof Soul_gameChatSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/session'
    | '/signin'
    | '/signup'
    | '/soul_game'
    | '/welcome'
    | '/map/$sessionId'
    | '/session/create'
    | '/session/join'
    | '/session/list'
    | '/session/'
    | '/soul_game/chat/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/soul_game'
    | '/welcome'
    | '/map/$sessionId'
    | '/session/create'
    | '/session/join'
    | '/session/list'
    | '/session'
    | '/soul_game/chat/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/session'
    | '/signin'
    | '/signup'
    | '/soul_game'
    | '/welcome'
    | '/map/$sessionId'
    | '/session/create'
    | '/session/join'
    | '/session/list'
    | '/session/'
    | '/soul_game/chat/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SessionRoute: typeof SessionRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  Soul_gameRoute: typeof Soul_gameRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  MapSessionIdRoute: typeof MapSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soul_game': {
      id: '/soul_game'
      path: '/soul_game'
      fullPath: '/soul_game'
      preLoaderRoute: typeof Soul_gameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/': {
      id: '/session/'
      path: '/'
      fullPath: '/session/'
      preLoaderRoute: typeof SessionIndexRouteImport
      parentRoute: typeof SessionRoute
    }
    '/session/list': {
      id: '/session/list'
      path: '/list'
      fullPath: '/session/list'
      preLoaderRoute: typeof SessionListRouteImport
      parentRoute: typeof SessionRoute
    }
    '/session/join': {
      id: '/session/join'
      path: '/join'
      fullPath: '/session/join'
      preLoaderRoute: typeof SessionJoinRouteImport
      parentRoute: typeof SessionRoute
    }
    '/session/create': {
      id: '/session/create'
      path: '/create'
      fullPath: '/session/create'
      preLoaderRoute: typeof SessionCreateRouteImport
      parentRoute: typeof SessionRoute
    }
    '/map/$sessionId': {
      id: '/map/$sessionId'
      path: '/map/$sessionId'
      fullPath: '/map/$sessionId'
      preLoaderRoute: typeof MapSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soul_game/chat/$sessionId': {
      id: '/soul_game/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/soul_game/chat/$sessionId'
      preLoaderRoute: typeof Soul_gameChatSessionIdRouteImport
      parentRoute: typeof Soul_gameRoute
    }
  }
}

interface SessionRouteChildren {
  SessionCreateRoute: typeof SessionCreateRoute
  SessionJoinRoute: typeof SessionJoinRoute
  SessionListRoute: typeof SessionListRoute
  SessionIndexRoute: typeof SessionIndexRoute
}

const SessionRouteChildren: SessionRouteChildren = {
  SessionCreateRoute: SessionCreateRoute,
  SessionJoinRoute: SessionJoinRoute,
  SessionListRoute: SessionListRoute,
  SessionIndexRoute: SessionIndexRoute,
}

const SessionRouteWithChildren =
  SessionRoute._addFileChildren(SessionRouteChildren)

interface Soul_gameRouteChildren {
  Soul_gameChatSessionIdRoute: typeof Soul_gameChatSessionIdRoute
}

const Soul_gameRouteChildren: Soul_gameRouteChildren = {
  Soul_gameChatSessionIdRoute: Soul_gameChatSessionIdRoute,
}

const Soul_gameRouteWithChildren = Soul_gameRoute._addFileChildren(
  Soul_gameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SessionRoute: SessionRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  Soul_gameRoute: Soul_gameRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  MapSessionIdRoute: MapSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
